version: '3.8'

services:
  serverapp:
    build:
      context: .
      dockerfile: ServerApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Database=aspnet-ProfessorOfTheYear;Username=postgres;Password=postgres
    ports:
      - "80:80"
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aspnet-ProfessorOfTheYear
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
volumes:
  postgres_data: