version: '3.8'

services:
  serverapp:
    build:
      context: .
      dockerfile: ServerApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Database=aspnet-ProfessorOfTheYear;Username=postgres;Password=postgres
    env_file:
      - ./ServerApp/.env
    ports:
      - "80:80"
    depends_on:
      - db
      - migrate
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aspnet-ProfessorOfTheYear
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  migrate:
    build:
      context: .
      dockerfile: ./ServerApp/Dockerfile.migrate
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=aspnet-ProfessorOfTheYear;Username=postgres;Password=postgres
    depends_on:
      - db

  backup:
    build:
      context: .
      dockerfile: ./ServerApp/Dockerfile.backup
    volumes:
      - postgres_backup:/backup
    depends_on:
      - db

volumes:
  postgres_data:
  postgres_backup: